name = "HelFEM"
uuid = "c0bd3504-f9fd-49c8-81ec-6baa9ade81f3"
authors = ["Morten Piibeleht <morten.piibeleht@gmail.com>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
HelFEM_jll = "584ea77b-75d0-51ad-9ad6-7fb559b95557"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
CxxWrap = "0.11"
HelFEM_jll = "0.1"
julia = "1.5"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LinearAlgebra", "SparseArrays"]
